# 예외 처리란?
예외 처리는 만일 코드를 실행하는데 에러가 생기는 부분을 찾아내고 에러 때문에 프로그램을 바로 종료하지 않고 계속 문제 없이 넘어가게 만들어주는 작업을 예외 처리라고 합니다.

만일 나누기 프로그램을 만들 때 분모를 0으로 입력하면 에러가 생깁니다.

이 상황에서 예외 처리를 하지 않는다면 에러가 나고 프로그램이 강재로 중단됩니다.

하지만 예외 처리를 한다면 사용자에게 분모가 0이 될 수 없다고 설명을 하고 넘어갈 수 있습니다.

# 예외 처리하는 방법
try{} 안에 문제가 될 수 있는 코드를 넣고 catch()를 사용해서 특정한 에러가 일어났을 때 프로그램을 중단하지 않고 바로 catch() 안에 있는 코드를 실행할 수 있습니다.

```
#include <iostream>
using namespace std;

double division(int a, int b) {
   if( b == 0 ) {
      throw "Division by zero condition!";
   }
   return (a/b);
}

int main () {
   int x = 50;
   int y = 0;
   double z = 0;

   try {
      z = division(x, y);
      cout << z << endl;
   } catch (const char* msg) {
     cerr << msg << endl;
   }

   return 0;
}
```

참고로 catch() 안에 있는 const char*은 에러 문자로 catch() 코드에서 msg 변수를 사용할 수 있게 도와줍니다.

# 에러 만들기
나만의 에러는 throw라는 키워드를 사용해서 만들 수 있습니다.

```
double division(int a, int b) {
   if( b == 0 ) {
      throw "Division by zero condition!";
   }
   return (a/b);
}
```

위의 함수에서 만일 b에 0을 넣게되면 "Division by zero condition!"이라는 에러가 생길 것입니다.
